services:
  webrtc-app:
    build: .
    container_name: webrtc-service
    ports:
      - "${HOST_IP}:${HTTP_PORT}:8080/tcp"
      - "${HOST_IP}:${TURN_PORT}:3478/tcp"
      - "0.0.0.0:${TURN_PORT}:3478/udp"
      - "0.0.0.0:${RELAY_PORT}:50000/udp"
    environment:
      - "HTTP_PORT=8080"
      - "TURN_PORT=3478"
      - "RELAY_PORT=50000"
      - "EXTERNAL_IP=${EXTERNAL_IP}"
      - "TURN_REALM=${TURN_REALM}"
      - "TURN_USERNAME=${TURN_USERNAME}"
      - "TURN_PASSWORD=${TURN_PASSWORD}"
